openapi: 3.0.1
info:
  title: STD21048 API
  description: 'Global description of my API'
  version: 1.0.0
servers:
 # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HEISOA2/STD21048/1.0.0
tags: 
 - name: Students

 - name: Courses
paths:
 /students:
    get:
      tags:
        - Students
      operationId: getStudents
      summary: Get all students
      description: Get all students with details
      responses:
        200: 
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    post: 
      tags:
        - Students
      operationId: createStudent
      summary : Create new student
      description: Create new student
      requestBody:
        description: Student to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        400:
          description: Bad request 
 /students/{id}:
    get:
      tags:
      - Students
      summary: Find students by Id 
      description: Get specified student
      parameters:
        - name: id
          in: path
          schema : 
            type : integer
          required : true
      responses:
        200: 
          description: Return the student
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    put:
      tags:
      - Students
      summary: Updated student
      description: Global modification
      operationId: updateStudent
      parameters: 
      - name: id
        in: path
        description: name that need to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Updated student object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        400:
          description: Invalid student supplied
          content: {}
        404:
          description: Student not found
          content: {}
    patch:
      tags:
      - Students
      summary: Updated student
      description: Partial modification.
      operationId: updatePartialStudent
      parameters:
      - name: id
        in: path
        description: |
          Possible updates on:
          * name : change
          * address : change
          * birth_date : change
       
        required: true
        schema: 
          type: string
      
      responses: 
        400:
          description: Invalid student supplied
          content: {}
        404:
          description: Student not found
          content: {}
          
    
    delete:
      tags:
      - Students
      summary: Delete student
      description: Delete.
      operationId: deleteStudent
      parameters:
      - name: id
        in: path
        description: The name that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return  the updated student
        400:
          description: Invalid student supplied
          content: {}
        404:
          description: Student not found
          content: {}
    

 

 /courses:
    get:
      tags:
        - Courses
      operationId: getCourses
      summary: Get all courses
      description: Get all courses with details
      parameters:
        - name: id
          in: query
          schema :
            type : integer
          required : true
      responses:
        200: 
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
    post: 
      tags:
        - Courses
      operationId: createCourse
      summary : Create new Course
      description: Create new course
      requestBody:
        description: courses to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourse'
        required: true
      responses:
        200:
          description: List of Courses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courses'
        400:
          description: Bad request 
    
          
 /courses/{id}: 
    get:
      tags:
        - Courses
      summary: Get all Courses
      description: Get all Courses with details
      parameters:
        - name: id
          in: path
          schema :
            type : integer
          required : true
      responses:
        200: 
          description: List of Courses
          content:
            application/json:
              schema:
                type : array
                items:
                  $ref: '#/components/schemas/Courses'
        400:
          description: Bad request
      
    

components:
  schemas:
    CreateStudent:
      type: object
      properties:
        name:
          type: string
          example: "Rakoto"
        birth_date:
          type: string
          format: date
          example: "2022-01-01"
    Student:
      allOf:
        - $ref: '#/components/schemas/CreateStudent'
      type: object
      properties:
        id:
          type: integer
          example: 10
    CreateCourse:
      type: object
      properties:
        id:
          type: integer
          example : 1
        code : 
          type: string
          example: "EL1"
        name : 
          type: string
          example: "api"
        Teacher :
          type : string
          example : "Harry"
        createdDate :
          type: string
          example : "2022-01-01"
    Courses :
      allOf:
        - $ref: '#/components/schemas/CreateCourse' 
      type: object
      properties:
        id:
          type: integer
          example : 1
        code : 
          type: string
          example: "EL1"
        name : 
          type: string
          example: "aPI"
        Teacher :
          type : string
          example : "Harry"
        createdDate :
          type: string
          example : "2022-01-01"
